// Generated by CoffeeScript 1.10.0
(function() {
  var Notifier, core,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  core = require('./core');

  Notifier = (function() {

    /**
     * @constructor
     */
    function Notifier() {
      this.s_generate = bind(this.s_generate, this);
      this.notify = bind(this.notify, this);
      core.logger.info('Notifier constructed.');
    }


    /**
     * @public
     * @param {string} message
     */

    Notifier.prototype.notify = function(message) {
      return core.logger.info("Notify. msg=" + message);
    };


    /**
     * @public
     * @static
     * @return {Notifier}
     */

    Notifier.prototype.s_generate = function() {
      var PushbulletNotifier;
      if (core.commander.apikey) {
        PushbulletNotifier = require('./pushbullet-notifier');
        return new PushbulletNotifier();
      } else {
        return new Notifier();
      }
    };

    return Notifier;

  })();

  module.exports = Notifier;

}).call(this);

//# sourceMappingURL=notifier.js.map
